'use client';

import { useEffect, useState } from 'react';
import { Navbar } from '@/components/layout/Navbar';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';

interface Generation {
    id: number;
    email: string;
    input_text: string;
    input_url: string;
    purpose: string;
    suggestions: string; // This contains the raw AI output usually
    is_flagged: boolean;
    created_at: string;
}

export default function AdminGenerations() {
    const [generations, setGenerations] = useState<Generation[]>([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        fetch('/api/admin/generations')
            .then(res => res.json())
            .then(data => {
                if (!data.error) setGenerations(data);
                setLoading(false);
            })
            .catch(err => {
                console.error(err);
                setLoading(false);
            });
    }, []);

    if (loading) return <div className="min-h-screen flex items-center justify-center">Loading...</div>;

    return (
        <div className="min-h-screen bg-muted/10">
            <Navbar />
            <main className="container mx-auto px-4 py-8">
                <h1 className="text-3xl font-bold mb-8">Content Monitoring</h1>

                <div className="space-y-6">
                    {generations.map((gen) => (
                        <Card key={gen.id} className={gen.is_flagged ? 'border-red-500' : ''}>
                            <CardHeader className="flex flex-row items-center justify-between pb-2">
                                <div className="flex flex-col">
                                    <CardTitle className="text-sm font-medium text-muted-foreground">
                                        Generated by {gen.email}
                                    </CardTitle>
                                    <span className="text-xs text-muted-foreground">
                                        {new Date(gen.created_at).toLocaleString()}
                                    </span>
                                </div>
                                {gen.is_flagged && <Badge variant="destructive">Flagged</Badge>}
                            </CardHeader>
                            <CardContent className="space-y-4">
                                <div className="grid grid-cols-2 gap-4 text-sm">
                                    <div>
                                        <span className="font-semibold">Input:</span>
                                        <p className="bg-muted p-2 rounded mt-1 line-clamp-3">
                                            {gen.input_text || gen.input_url || 'N/A'}
                                        </p>
                                    </div>
                                    <div>
                                        <span className="font-semibold">Purpose:</span>
                                        <p className="bg-muted p-2 rounded mt-1">
                                            {gen.purpose}
                                        </p>
                                    </div>
                                </div>
                            </CardContent>
                        </Card>
                    ))}
                </div>
            </main>
        </div>
    );
}
